# Generated by Django 4.0.3 on 2022-04-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('category', models.CharField(max_length=40)),
                ('details', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
